// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package shbot

type Book struct {
	ID    int64
	Title *string
	Year  *int64
}

type BookSongJoin struct {
	ID               int64
	BookID           *int64
	SongID           *int64
	PageNum          *string
	Text             *string
	WordsAttribution *string
	Keys             *string
	Times            *string
	Orientation      *string
}

type Leader struct {
	ID            int64
	Name          *string
	LessonCount   *int64
	SongEntropy   *float64
	Top20Count    *int64
	LocationCount *int64
}

type LeaderNameAlias struct {
	ID       int64
	LeaderID *int64
	Name     *string
	Alias    *string
	Type     *string
}

type LeaderNameInvalid struct {
	ID   int64
	Name *string
}

type LeaderSongDetails struct {
	Name                    *string
	LessonCount             *int64
	LessonRank              *int64
	TotalNumLeaderLocations *int64
	TotalNumLeanderLessons  *int64
	TotalNumSongLessons     *int64
	SongRank                *int64
	SongTitle               *string
	SongMeter               *string
	SongTimeSignature       *string
	SongKeys                *string
	SongPage                *string
	SongBookTitle           *string
	SongBookYear            *int64
	SongMusicAttribution    *string
	SongWordsAttribution    *string
}

type LeaderSongStat struct {
	ID          int64
	LeaderID    *int64
	SongID      *int64
	LessonCount *int64
	LessonRank  *int64
}

type Location struct {
	ID            int64
	Name          *string
	URL           *string
	Notes         *string
	GpsLat        *float64
	GpsLong       *float64
	Address       *string
	City          *string
	County        *string
	StateProvince *string
	PostalCode    *string
	Country       *string
}

type Minute struct {
	ID          int64
	Name        *string
	Location    *string
	Date        *string
	Minutes     *string
	Year        *int64
	IsDenson    *int64
	GoodCt      *int64
	ErrCt       *int64
	AmbCt       *int64
	CorrCt      *int64
	ProbCt      *int64
	TotalCt     *int64
	ProbPercent *float64
	DensonYear  *float64
	AudioURL    *string
	DateOrdinal *int64
	IsVirtual   *int64
}

type MinutesDetails struct {
	MinutesID             int64
	MinutesName           *string
	MinutesLocation       *string
	MinutesDate           *string
	MinutesYear           *int64
	DensonYear            *float64
	MinutesBody           *string
	IsDenson              *int64
	Singing               *string
	LocationName          *string
	LocationCountry       *string
	LocationStateProvince *string
	LocationCity          *string
}

type MinutesLocationJoin struct {
	ID         int64
	MinutesID  *int64
	LocationID *int64
}

type MinutesSingingJoin struct {
	ID           int64
	MinutesID    *int64
	SingingID    *int64
	SingingIndex *int64
	SingingEnd   *int64
}

type Singing struct {
	ID   int64
	Name *string
}

type Song struct {
	ID               int64
	Title            *string
	Meter            *string
	MusicAttribution *string
	ThreeLiner       *int64
}

type SongDetails struct {
	BookID           *int64
	SongID           *int64
	PageNum          *string
	Text             *string
	Keys             *string
	Times            *string
	Orientation      *string
	BookTitle        *string
	BookYear         *int64
	SongTitle        *string
	Meter            *string
	MusicAttribution *string
	WordsAttribution *string
}

type SongLeaderJoin struct {
	ID        int64
	SongID    *int64
	LeaderID  *int64
	MinutesID *int64
	LessonID  *int64
	AudioURL  *string
}

type SongNeighbor struct {
	ID         int64
	FromSongID *int64
	ToSongID   *int64
	Rank       *int64
}

type SongStat struct {
	ID          int64
	SongID      *int64
	Year        *int64
	LessonCount *int64
	Rank        *int64
}
