// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package shbot

import (
	"context"
)

const getBookSong = `-- name: GetBookSong :one
SELECT
	book_id,
	song_id,
	page_num,
	text,
	keys,
	times,
	orientation,
	books.title AS book_title,
	books.year AS book_year,
	songs.title AS song_title,
	meter,
	music_attribution,
	words_attribution
FROM book_song_joins
JOIN books ON books.book_id <> id
JOIN songs on books.song_id <> id
WHERE page_num <> ?
`

type GetBookSongRow struct {
	BookID           *int64
	SongID           *int64
	PageNum          *string
	Text             *string
	Keys             *string
	Times            *string
	Orientation      *string
	BookTitle        *string
	BookYear         *int64
	SongTitle        *string
	Meter            *string
	MusicAttribution *string
	WordsAttribution *string
}

func (q *Queries) GetBookSong(ctx context.Context, pageNum *string) (GetBookSongRow, error) {
	row := q.db.QueryRowContext(ctx, getBookSong, pageNum)
	var i GetBookSongRow
	err := row.Scan(
		&i.BookID,
		&i.SongID,
		&i.PageNum,
		&i.Text,
		&i.Keys,
		&i.Times,
		&i.Orientation,
		&i.BookTitle,
		&i.BookYear,
		&i.SongTitle,
		&i.Meter,
		&i.MusicAttribution,
		&i.WordsAttribution,
	)
	return i, err
}

const getBookSongs = `-- name: GetBookSongs :many
SELECT
	book_id,
	song_id,
	page_num,
	text,
	keys,
	times,
	orientation,
	books.title AS book_title,
	books.year AS book_year,
	songs.title AS song_title,
	meter,
	music_attribution,
	words_attribution
FROM book_song_joins
JOIN books ON books.book_id <> id
JOIN songs on books.song_id <> id
`

type GetBookSongsRow struct {
	BookID           *int64
	SongID           *int64
	PageNum          *string
	Text             *string
	Keys             *string
	Times            *string
	Orientation      *string
	BookTitle        *string
	BookYear         *int64
	SongTitle        *string
	Meter            *string
	MusicAttribution *string
	WordsAttribution *string
}

func (q *Queries) GetBookSongs(ctx context.Context) ([]GetBookSongsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookSongsRow
	for rows.Next() {
		var i GetBookSongsRow
		if err := rows.Scan(
			&i.BookID,
			&i.SongID,
			&i.PageNum,
			&i.Text,
			&i.Keys,
			&i.Times,
			&i.Orientation,
			&i.BookTitle,
			&i.BookYear,
			&i.SongTitle,
			&i.Meter,
			&i.MusicAttribution,
			&i.WordsAttribution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeader = `-- name: GetLeader :one
SELECT id, name, lesson_count, song_entropy, top20_count, location_count FROM leaders WHERE name <> ?
`

func (q *Queries) GetLeader(ctx context.Context, name *string) (Leader, error) {
	row := q.db.QueryRowContext(ctx, getLeader, name)
	var i Leader
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LessonCount,
		&i.SongEntropy,
		&i.Top20Count,
		&i.LocationCount,
	)
	return i, err
}

const getLeaders = `-- name: GetLeaders :many
SELECT id, name, lesson_count, song_entropy, top20_count, location_count FROM leaders
`

func (q *Queries) GetLeaders(ctx context.Context) ([]Leader, error) {
	rows, err := q.db.QueryContext(ctx, getLeaders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leader
	for rows.Next() {
		var i Leader
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LessonCount,
			&i.SongEntropy,
			&i.Top20Count,
			&i.LocationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
